# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/waitwalker/PodSepcs.git'


target 'StudyHard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'DeviceHelper'

  # Pods for StudyHard

  target 'StudyHardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StudyHardUITests' do
    # Pods for testing
  end

end
