# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'umeng_ios_demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for umeng_ios_demo
  pod 'UMCCommon'
  pod 'UMCSecurityPlugins'
  pod 'UMCCommonLog'
  pod 'UMCAnalytics'
end
